[package]
name = "whitewash"
version = "0.1.0"
edition = "2018"
authors = ["Vivek Kushwaha <yoursvivek@users.noreply.github.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
ammonia = "3.1.2"
pyo3 = {version = "0.15.1", features = ["extension-module"]}
