[project]
name = "whitewash"
version = "0.1.0"
description = "whitewash html"
authors = [
  {name = "Vivek Kushwaha", email = "yoursvivek@users.noreply.github.com" },
]
license = {file = "LICENSE-MIT"}

[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
